export type BelgiumCity = {
  name: string;
  slug: string;
};

export type BelgiumProvince = {
  id: string;
  name: string;
  nameNl: string;
  region: "Flanders" | "Wallonia" | "Brussels";
  cities: BelgiumCity[];
};

function city(name: string, slug?: string): BelgiumCity {
  return {
    name,
    slug: slug ?? name.toLowerCase().replace(/\s+/g, "-").replace(/'/g, ""),
  };
}

/** SEO location index, expand cities as you add service areas. */
export const belgiumProvinces: BelgiumProvince[] = [
  {
    id: "west-vlaanderen",
    name: "West Flanders",
    nameNl: "West-Vlaanderen",
    region: "Flanders",
    cities: [
      city("Brugge"),
      city("Kortrijk"),
      city("Oostende"),
      city("Roeselare"),
      city("Ieper"),
      city("Knokke-Heist"),
      city("Waregem"),
      city("Diksmuide"),
      city("Tielt"),
      city("Harelbeke"),
      city("Menen"),
      city("Poperinge"),
      city("Torhout"),
      city("Veurne"),
      city("Blankenberge"),
      city("Nieuwpoort"),
      city("De Panne"),
      city("Izegem"),
      city("Oostkamp"),
      city("Zedelgem"),
      city("Kuurne"),
      city("Ingelmunster"),
      city("Ledegem"),
      city("Moorslede"),
      city("Staden"),
      city("Anzegem"),
      city("Ardooie"),
      city("Avelgem"),
      city("Beernem"),
      city("Damme"),
      city("De Haan"),
      city("Deerlijk"),
      city("Dentergem"),
      city("Gistel"),
      city("Heuvelland"),
      city("Hooglede"),
      city("Ichtegem"),
      city("Jabbeke"),
      city("Koekelare"),
      city("Koksijde"),
      city("Kortemark"),
      city("Langemark-Poelkapelle"),
      city("Lichtervelde"),
      city("Lo-Reninge"),
      city("Mesen"),
      city("Meulebeke"),
      city("Middelkerke"),
      city("Oostrozebeke"),
      city("Spiere-Helkijn"),
      city("Wervik"),
      city("Wielsbeke"),
      city("Wingene"),
      city("Zonnebeke"),
    ],
  },
  {
    id: "oost-vlaanderen",
    name: "East Flanders",
    nameNl: "Oost-Vlaanderen",
    region: "Flanders",
    cities: [
      city("Gent"),
      city("Aalst"),
      city("Sint-Niklaas"),
      city("Dendermonde"),
      city("Lokeren"),
      city("Eeklo"),
      city("Oudenaarde"),
      city("Ronse"),
      city("Wetteren"),
      city("Ninove"),
      city("Zottegem"),
      city("Temse"),
      city("Beveren"),
      city("Destelbergen"),
      city("Merelbeke"),
      city("Deinze"),
      city("Geraardsbergen"),
      city("Lede"),
      city("Berlare"),
      city("Buggenhout"),
      city("Hamme"),
      city("Laarne"),
      city("Lochristi"),
      city("Maldegem"),
      city("Nevele"),
      city("Sint-Lievens-Houtem"),
      city("Sint-Martens-Latem"),
      city("Waasmunster"),
      city("Zele"),
      city("Assenede"),
      city("Brakel"),
      city("Evergem"),
      city("Haaltert"),
      city("Herzele"),
      city("Kluisbergen"),
      city("Kruibeke"),
      city("Lebbeke"),
      city("Lierde"),
      city("Maarkedal"),
      city("Melle"),
      city("Moerbeke"),
      city("Nazareth"),
      city("Sint-Gillis-Waas"),
      city("Stekene"),
      city("Ternat"),
    ],
  },
  {
    id: "antwerpen",
    name: "Antwerp",
    nameNl: "Antwerpen",
    region: "Flanders",
    cities: [
      city("Antwerpen"),
      city("Mechelen"),
      city("Turnhout"),
      city("Mol"),
      city("Geel"),
      city("Herentals"),
      city("Lier"),
      city("Hoogstraten"),
      city("Brasschaat"),
      city("Schoten"),
      city("Mortsel"),
      city("Boom"),
      city("Willebroek"),
      city("Heist-op-den-Berg"),
      city("Duffel"),
    ],
  },
  {
    id: "limburg",
    name: "Limburg",
    nameNl: "Limburg",
    region: "Flanders",
    cities: [
      city("Hasselt"),
      city("Genk"),
      city("Sint-Truiden"),
      city("Tongeren"),
      city("Beringen"),
      city("Lommel"),
      city("Maasmechelen"),
      city("Houthalen-Helchteren"),
      city("Bilzen"),
      city("Lanaken"),
    ],
  },
  {
    id: "vlaams-brabant",
    name: "Flemish Brabant",
    nameNl: "Vlaams-Brabant",
    region: "Flanders",
    cities: [
      city("Leuven"),
      city("Vilvoorde"),
      city("Diest"),
      city("Aarschot"),
      city("Tienen"),
      city("Halle"),
      city("Zaventem"),
      city("Grimbergen"),
      city("Dilbeek"),
      city("Asse"),
    ],
  },
  {
    id: "henegouwen",
    name: "Hainaut",
    nameNl: "Henegouwen",
    region: "Wallonia",
    cities: [
      city("Charleroi"),
      city("Mons"),
      city("La Louvière"),
      city("Tournai"),
      city("Mouscron"),
      city("Châtelet"),
      city("Binche"),
    ],
  },
  {
    id: "luik",
    name: "Liège",
    nameNl: "Luik",
    region: "Wallonia",
    cities: [
      city("Liège"),
      city("Seraing"),
      city("Verviers"),
      city("Herstal"),
      city("Huy"),
      city("Eupen"),
    ],
  },
  {
    id: "namen",
    name: "Namur",
    nameNl: "Namen",
    region: "Wallonia",
    cities: [
      city("Namur"),
      city("Andenne"),
      city("Gembloux"),
      city("Ciney"),
      city("Dinant"),
    ],
  },
  {
    id: "luxemburg",
    name: "Luxembourg",
    nameNl: "Luxemburg",
    region: "Wallonia",
    cities: [
      city("Arlon"),
      city("Bastogne"),
      city("Marche-en-Famenne"),
      city("Virton"),
    ],
  },
  {
    id: "waals-brabant",
    name: "Walloon Brabant",
    nameNl: "Waals-Brabant",
    region: "Wallonia",
    cities: [
      city("Wavre"),
      city("Nivelles"),
      city("Ottignies-Louvain-la-Neuve"),
      city("Tubize"),
    ],
  },
  {
    id: "brussel",
    name: "Brussels-Capital",
    nameNl: "Brussels Hoofdstedelijk Gewest",
    region: "Brussels",
    cities: [
      city("Brussel"),
      city("Elsene"),
      city("Schaarbeek"),
      city("Anderlecht"),
      city("Ukkel"),
      city("Sint-Gillis"),
      city("Etterbeek"),
    ],
  },
];

export const allBelgiumCities = belgiumProvinces.flatMap((province) =>
  province.cities.map((c) => ({ ...c, province })),
);

export function getCityBySlug(slug: string) {
  return allBelgiumCities.find((entry) => entry.slug === slug) ?? null;
}

export const locationsPagePath = "/locations" as const;

export function cityLocationPath(slug: string): string {
  return `${locationsPagePath}/${slug}`;
}
